### PR TITLE
fixed array, added explosions, added bullet collision detection

### PR DESCRIPTION
**Pull request by HamishMeares**
I fixed the bug with the first enemy being in the wrong spot.
Added simple explosion
Added bullet collision and explosion with subsequent removal of bullet and rendering enemy dead

### CODE REVIEW

**Comment by peternewman22** [comment]
Oooh this is exciting! I had to watch a Daniel Shiffman thing to get my head around the terminology, but I think I get it now. Yay!

**Comment by HamishMeares** [comment]
Cool. Yay us. We will master git… eventually. :)
I found the yak shaving bug for the git upstream stuff (I was using master instead of main)
I had fun doing the collisions

**Comment by peternewman22** [comment]
Looks good. Weirdly, it doesn't play the death animation on some of the bottom middle rows. The enemy stops being displayed, but it doesn't show the explosion. Not sure why. I've just had a play with repositioning the enemies at the beginning of the screen. I don't understand why my code isn't working, but they're a bit more central now.

**Comment by peternewman22** [comment]
I also don't know why it's "main" and not "master" - I didn't make that change to my knowledge

**Comment by peternewman22** [comment]
So I may have gone in and adapted your explosion code so that you get an animated, persistent but fading explosion object originating at the point of impact. Keen to work on this more on Monday.

**Pull request merged**
